spring:
  application:
    name: TF_Java_2026_IntroSpringAPI
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/intro_spring_api}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:migration
    default-schema: public
    schemas: public
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  cache:
    type: redis
    redis:
      time-to-live: 900000
jwt:
    secret: ${JWT_SECRET}
    accessTokenValidity: 900
    refreshTokenValidity: 604800
logging:
  file:
    path: logs
  level:
    root: INFO
server:
  port: 8080