CREATE SEQUENCE IF NOT EXISTS revinfo_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE game
(
    is_enable    BOOLEAN                                  NOT NULL,
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(50)                              NOT NULL,
    release_year INTEGER                                  NOT NULL,
    price        INTEGER                                  NOT NULL,
    image_url    VARCHAR(255),
    CONSTRAINT pk_game PRIMARY KEY (id)
);

CREATE TABLE revchanges
(
    rev        BIGINT NOT NULL,
    entityname VARCHAR(255)
);

CREATE TABLE revinfo
(
    rev      BIGINT NOT NULL,
    revtstmp BIGINT,
    CONSTRAINT pk_revinfo PRIMARY KEY (rev)
);

CREATE TABLE role_
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50)                              NOT NULL,
    CONSTRAINT pk_role_ PRIMARY KEY (id)
);

CREATE TABLE user_
(
    is_enable BOOLEAN                                  NOT NULL,
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username  VARCHAR(50)                              NOT NULL,
    birthday  date,
    password  VARCHAR(255)                             NOT NULL,
    role_id   INTEGER,
    CONSTRAINT pk_user_ PRIMARY KEY (id)
);

ALTER TABLE role_
    ADD CONSTRAINT uc_role__name UNIQUE (name);

ALTER TABLE user_
    ADD CONSTRAINT uc_user__username UNIQUE (username);

ALTER TABLE user_
    ADD CONSTRAINT FK_USER__ON_ROLE FOREIGN KEY (role_id) REFERENCES role_ (id);

ALTER TABLE revchanges
    ADD CONSTRAINT fk_revchanges_on_default_tracking_modified_entities_changelog FOREIGN KEY (rev) REFERENCES revinfo (rev);